name: Generate Video

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-dejavu fonts-liberation

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gTTS Pillow moviepy pydub icrawler

      # Run the script
      - name: Run video generation script
        run: python main.py

      # Upload the generated video as an artifact
      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-video
          path: output/output_video.mp4
          retention-days: 7
