name: Generate Video

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }} # Use PAT for push

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-dejavu fonts-liberation
          ffmpeg -version

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow==10.4.0 moviepy==1.0.3 requests==2.32.3 numpy==1.26.4 icrawler==0.6.10 google-cloud-texttospeech gspread
          pip show moviepy
          pip show Pillow requests numpy icrawler google-cloud-texttospeech gspread

      # Set up Google TTS credentials
      - name: Set up Google TTS credentials
        env:
          GOOGLE_TTS_KEY: ${{ secrets.GOOGLE_TTS_KEY }}
        run: |
          echo "$GOOGLE_TTS_KEY" > google_tts_key.json
          ls -l google_tts_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/google_tts_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS" >> $GITHUB_ENV

      # Set up Google Sheets credentials
      - name: Set up Google Sheets credentials
        env:
          GOOGLE_SHEETS_KEY: ${{ secrets.GOOGLE_SHEETS_KEY }}
        run: |
          echo "$GOOGLE_SHEETS_KEY" > google_sheets_key.json
          ls -l google_sheets_key.json

      # Run the script
      - name: Run video generation script
        run: python main.py

      # Commit video to output folder
      - name: Commit video to output folder
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Ensure output folder exists
          mkdir -p output
          # Move video to output (already created by main.py)
          git add output/output_video_*.mp4
          git commit -m "Add video for row $ROW_NUM" || echo "No new video to commit"
          git push
        env:
          ROW_NUM: $(cat output/selected_row_num.txt 2>/dev/null || echo "unknown")

      # Update sheet with raw URL
      - name: Update sheet with raw URL
        if: success()
        run: python update_sheet.py

      # Cleanup old videos (older than 90 days)
      - name: Cleanup old videos
        if: always()
        run: |
          # Get current timestamp and 90 days ago (in seconds)
          CURRENT_TIME=$(date +%s)
          THREE_MONTHS_AGO=$((CURRENT_TIME - 90*24*60*60))
          # List commits touching output folder
          COMMITS=$(git log --name-only --pretty=format:%H:%ct -- output | grep -B1 'output/output_video_' | grep -v '^--$' | grep -v '^output/')
          while read -r COMMIT_HASH COMMIT_TIME; do
            if [ -n "$COMMIT_HASH" ] && [ "$COMMIT_TIME" -lt "$THREE_MONTHS_AGO" ]; then
              echo "Found old commit: $COMMIT_HASH at $(date -d @$COMMIT_TIME)"
              # Get files changed in this commit
              FILES=$(git show --name-only --pretty="" $COMMIT_HASH | grep '^output/output_video_.*\.mp4$')
              for FILE in $FILES; do
                echo "Deleting old video: $FILE"
                git rm $FILE
              done
            fi
          done <<< "$COMMITS"
          # Commit cleanup if there were deletions
          if git status --porcelain | grep '^D'; then
            git commit -m "Cleanup videos older than 90 days"
            git push
          else
            echo "No old videos to clean up"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
