name: Generate Video

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # Cache pip dependencies for faster runs

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-dejavu fonts-liberation
          ffmpeg -version # Verify ffmpeg installation

      # Install Python dependencies with specific versions
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow==10.4.0 moviepy==1.0.3 requests==2.32.3 numpy==1.26.4 icrawler==0.6.10 google-cloud-texttospeech
          pip show moviepy # Verify moviepy installation
          pip show Pillow requests numpy icrawler google-cloud-texttospeech # Verify other dependencies

      # Create Google Cloud credentials file from secret
      - name: Set up Google Cloud credentials
        env:
          GOOGLE_TTS_KEY: ${{ secrets.GOOGLE_TTS }}
        run: |
          echo "$GOOGLE_TTS_KEY" > google_tts_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/google_tts_key.json

      # Run the script
      - name: Run video generation script
        run: python main.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $(pwd)/google_tts_key.json

      # Upload the generated video as an artifact
      - name: Upload video artifact
        if: success() # Only upload if the script runs successfully
        uses: actions/upload-artifact@v4
        with:
          name: generated-video
          path: output/output_video.mp4
          retention-days: 7
