name: Generate Video

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-video:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # Cache pip dependencies for faster runs

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-dejavu fonts-liberation
          ffmpeg -version # Verify ffmpeg installation

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow==10.4.0 moviepy==1.0.3 requests==2.32.3 numpy==1.26.4 icrawler==0.6.10 google-cloud-texttospeech gspread google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 oauth2client
          pip show moviepy
          pip show Pillow requests numpy icrawler google-cloud-texttospeech gspread google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 oauth2client

      # Set up Google Cloud credentials for TTS
      - name: Set up Google TTS credentials
        env:
          GOOGLE_TTS_KEY: ${{ secrets.GOOGLE_TTS_KEY }}
        run: |
          echo "$GOOGLE_TTS_KEY" > google_tts_key.json
          ls -l google_tts_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/google_tts_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS" >> $GITHUB_ENV

      # Set up Google Sheets credentials
      - name: Set up Google Sheets credentials
        env:
          GOOGLE_SHEETS_KEY: ${{ secrets.GOOGLE_SHEETS_KEY }}
        run: |
          echo "$GOOGLE_SHEETS_KEY" > google_sheets_key.json
          ls -l google_sheets_key.json

      # Run the script
      - name: Run video generation script
        run: python main.py

      # Upload video artifact
      - name: Upload video artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: generated-video
          path: output/output_video.mp4
          retention-days: 1
